//=========================================================
// src/EFM8SB10F2G_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

/*
 * Copyright (c) 2019-2020, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include "InitDevice.h"
#include "gpio.h"
#include "power.h"

#define APP_VERSION_INFO "\r\nFW VER: 0.11"

static char *uart_app_version_p = APP_VERSION_INFO;
void (*run_power_state)(void);
// $[Generated Includes]
// [Generated Includes]$

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void)
{
    // $[SiLabs Startup]
    // [SiLabs Startup]$
}

void uart_send_version_info(void)
{   // print FW version info through UART
    while ((*uart_app_version_p) != '\0')
    {
        SBUF0 = *uart_app_version_p;
        uart_app_version_p++;
        while (SCON0_TI == 0)
        {
            // do nothing
        }
        SCON0_TI = 0;
    }
    // Timer1 will be used for signal controlling
    TCON_TR1 = 0; // Stop Timer 1
    TMOD = (TMOD & (~TMOD_T1M__FMASK)) | TMOD_T1M__MODE1; // Clear mode and set to mode 1
    CKCON0 &= ~CKCON0_T1M__SYSCLK; // Use prescale clock
    SCON0 &= ~SCON0_TI__SET; // Disable TX
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main(void)
{
    uint8_t PMU0CF_shadow;
    uint8_t b;
    bit save_ie_ea;

    // Call hardware initialization routine
    enter_DefaultMode_from_RESET();

    uart_send_version_info(); // Send FW version through UART

    init_gpio();
    init_power();

    // Enable interrupt after init
    IE_EA = 1;

    while (1)
    {
        (*run_power_state)();
        // Note: Execution time from here to
        // 1. right before goto IDLE - 5.2 us
        // 2. right before goto SLEEP - 18 us

        // Do nothing if in powering on/off state,
        // in case any timer expired right before going to idle
        if (power_event == NONE)
        {
            // only go to sleep in power off state, without timer2/3 running
            // if finish debouncing before checking timer2, timer3 will be running
            // if timer3 expired before the checking, we will need to extend timer3 trigger time.
            if (power_off_state && !TMR2CN0_TR2)
            {
                save_ie_ea = IE_EA;
                IE_EA = 0;                  // Disable interrupts

                // if any port match triggers debouncing right before going to sleep,
                // do not go to sleep until finish debouncing.
                if (!TMR2CN0_TR2 && ((TMR3CN0 & TMR3CN0_TR3__RUN) == 0))
                {
                    // goto SLEEP
                    PMU0CF = 0x20;              // Clear previous wake events
                    PMU0CF = 0x82;              // Set sleep bit and PortMatch wakeup bit

                    // 4 NOPs required as stated in Reference Manual
                    NOP();
                    NOP();
                    NOP();
                    NOP();

                    // Wake up and store PMU0CF, clear all wakeup events and re-enable interrupts
                    PMU0CF_shadow = PMU0CF;
                    PMU0CF = 0x20;

                    // If wakeup source is RSTb, do not go to sleep for 20us
                    if (PMU0CF_shadow & 0x10)
                    {
                        for (b = 15; b > 0; b--)
                        {
                            // do nothing
                        }
                    }
                }
                else
                {
                    // do nothing
                }

                IE_EA = save_ie_ea;
            }
            else
            {
                // goto IDLE
                PCON0 |= 0x01; // set IDLE bit
                PCON0 = PCON0; // Go into idle mode fully after a 3-cycle dummy instruction
            }
        }
    }
}
