//=========================================================
// src/InitDevice.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

/*
 * Copyright (c) 2019-2020, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */

// USER INCLUDES
#include <SI_EFM8SB1_Register_Enums.h>
#include "InitDevice.h"

// USER PROTOTYPES
// USER FUNCTIONS

// $[Library Includes]
// [Library Includes]$

//==============================================================================
// enter_DefaultMode_from_RESET
//==============================================================================
extern void enter_DefaultMode_from_RESET(void)
{
    // $[Config Calls]
    // Save the SFRPAGE
    uint8_t SFRPAGE_save = SFRPAGE;
    PCA_0_enter_DefaultMode_from_RESET();
    PCACH_2_enter_DefaultMode_from_RESET();
    CMP_0_enter_DefaultMode_from_RESET();
    PORTS_0_enter_DefaultMode_from_RESET();
    PORTS_1_enter_DefaultMode_from_RESET();
    PBCFG_0_enter_DefaultMode_from_RESET();
    CLOCK_0_enter_DefaultMode_from_RESET();
    TIMER01_0_enter_DefaultMode_from_RESET();
    TIMER_SETUP_0_enter_DefaultMode_from_RESET();
    INTERRUPT_0_enter_DefaultMode_from_RESET();
    // Restore the SFRPAGE
    SFRPAGE = SFRPAGE_save;
    // [Config Calls]$
}

//================================================================================
// PORTS_1_enter_DefaultMode_from_RESET
//================================================================================
extern void PORTS_1_enter_DefaultMode_from_RESET(void)
{
    // $[P1 - Port 1 Pin Latch]
    /***********************************************************************
     - P1.0 is high. Set P1.0 to drive or float high
     - P1.1 is high. Set P1.1 to drive or float high
     - P1.2 is high. Set P1.2 to drive or float high
     - P1.3 is low. Set P1.3 to drive low
     - P1.5 is low. Set P1.5 to drive low
     - P1.6 is high. Set P1.6 to drive or float high
     - P1.7 is high. Set P1.7 to drive or float high
     ***********************************************************************/
    P1 = P1_B0__HIGH | P1_B1__HIGH | P1_B2__HIGH | P1_B3__LOW | P1_B5__LOW
            | P1_B6__HIGH | P1_B7__HIGH;
    // [P1 - Port 1 Pin Latch]$

    // $[P1MDOUT - Port 1 Output Mode]
    /***********************************************************************
     - P1.0 output is open-drain
     - P1.1 output is open-drain
     - P1.2 output is open-drain
     - P1.3 output is push-pull
     - P1.5 output is push-pull
     - P1.6 output is open-drain
     - P1.7 output is open-drain
     ***********************************************************************/
    P1MDOUT = P1MDOUT_B0__OPEN_DRAIN | P1MDOUT_B1__OPEN_DRAIN
            | P1MDOUT_B2__OPEN_DRAIN | P1MDOUT_B3__PUSH_PULL
            | P1MDOUT_B5__PUSH_PULL | P1MDOUT_B6__OPEN_DRAIN
            | P1MDOUT_B7__OPEN_DRAIN;
    // [P1MDOUT - Port 1 Output Mode]$

    // $[P1MDIN - Port 1 Input Mode]
    /***********************************************************************
     - P1.0 pin is configured for analog mode
     - P1.1 pin is configured for digital mode
     - P1.2 pin is configured for digital mode
     - P1.3 pin is configured for digital mode
     - P1.5 pin is configured for digital mode
     - P1.6 pin is configured for digital mode
     - P1.7 pin is configured for digital mode
     ***********************************************************************/
    P1MDIN = P1MDIN_B0__ANALOG | P1MDIN_B1__DIGITAL | P1MDIN_B2__DIGITAL
            | P1MDIN_B3__DIGITAL | P1MDIN_B5__DIGITAL | P1MDIN_B6__DIGITAL
            | P1MDIN_B7__DIGITAL;
    // [P1MDIN - Port 1 Input Mode]$

    // $[P1SKIP - Port 1 Skip]
    /***********************************************************************
     - P1.0 pin is skipped by the crossbar
     - P1.1 pin is not skipped by the crossbar
     - P1.2 pin is not skipped by the crossbar
     - P1.3 pin is not skipped by the crossbar
     - P1.5 pin is not skipped by the crossbar
     - P1.6 pin is not skipped by the crossbar
     - P1.7 pin is not skipped by the crossbar
     ***********************************************************************/
    P1SKIP = P1SKIP_B0__SKIPPED | P1SKIP_B1__NOT_SKIPPED
            | P1SKIP_B2__NOT_SKIPPED | P1SKIP_B3__NOT_SKIPPED
            | P1SKIP_B5__NOT_SKIPPED | P1SKIP_B6__NOT_SKIPPED
            | P1SKIP_B7__NOT_SKIPPED;
    // [P1SKIP - Port 1 Skip]$

    // $[Missing Pin Skip]
    // Skip any pins that are not available on this package
    P1SKIP |= P1SKIP_B4__SKIPPED;
    // [Missing Pin Skip]$

    // $[P1MASK - Port 1 Mask]
    /***********************************************************************
     - P1.0 pin logic value is ignored and will not cause a port mismatch
     event
     - P1.1 pin logic value is compared to P1MAT.1
     - P1.2 pin logic value is ignored and will not cause a port mismatch
     event
     - P1.3 pin logic value is ignored and will not cause a port mismatch
     event
     - P1.5 pin logic value is ignored and will not cause a port mismatch
     event
     - P1.6 pin logic value is ignored and will not cause a port mismatch
     event
     - P1.7 pin logic value is ignored and will not cause a port mismatch
     event
     ***********************************************************************/
    P1MASK = P1MASK_B0__IGNORED | P1MASK_B1__COMPARED | P1MASK_B2__IGNORED
            | P1MASK_B3__IGNORED | P1MASK_B5__IGNORED | P1MASK_B6__IGNORED
            | P1MASK_B7__IGNORED;
    // [P1MASK - Port 1 Mask]$

    // $[P1MAT - Port 1 Match]
    // [P1MAT - Port 1 Match]$

    // $[P1DRV - Port 1 Drive Strength]
    // [P1DRV - Port 1 Drive Strength]$
}

extern void PORTS_0_enter_DefaultMode_from_RESET(void)
{
    // $[P0 - Port 0 Pin Latch]
    // [P0 - Port 0 Pin Latch]$

    // $[P0MDOUT - Port 0 Output Mode]
    /***********************************************************************
     - P0.0 output is open-drain
     - P0.1 output is open-drain
     - P0.2 output is open-drain
     - P0.3 output is open-drain
     - P0.4 output is push-pull
     - P0.5 output is open-drain
     - P0.6 output is open-drain
     - P0.7 output is open-drain
     ***********************************************************************/
    P0MDOUT = P0MDOUT_B0__OPEN_DRAIN | P0MDOUT_B1__OPEN_DRAIN
            | P0MDOUT_B2__OPEN_DRAIN | P0MDOUT_B3__OPEN_DRAIN
            | P0MDOUT_B4__PUSH_PULL | P0MDOUT_B5__OPEN_DRAIN
            | P0MDOUT_B6__OPEN_DRAIN | P0MDOUT_B7__OPEN_DRAIN;
    // [P0MDOUT - Port 0 Output Mode]$

    // $[P0MDIN - Port 0 Input Mode]
    // [P0MDIN - Port 0 Input Mode]$

    // $[P0SKIP - Port 0 Skip]
    // [P0SKIP - Port 0 Skip]$

    // $[P0MASK - Port 0 Mask]
    /***********************************************************************
     - P0.0 pin logic value is compared to P0MAT.0
     - P0.1 pin logic value is ignored and will not cause a port mismatch
     event
     - P0.2 pin logic value is compared to P0MAT.2
     - P0.3 pin logic value is ignored and will not cause a port mismatch
     event
     - P0.4 pin logic value is ignored and will not cause a port mismatch
     event
     - P0.5 pin logic value is ignored and will not cause a port mismatch
     event
     - P0.6 pin logic value is compared to P0MAT.6
     - P0.7 pin logic value is compared to P0MAT.7
     ***********************************************************************/
    P0MASK = P0MASK_B0__COMPARED | P0MASK_B1__IGNORED | P0MASK_B2__COMPARED
            | P0MASK_B3__IGNORED | P0MASK_B4__IGNORED | P0MASK_B5__IGNORED
            | P0MASK_B6__COMPARED | P0MASK_B7__COMPARED;
    // [P0MASK - Port 0 Mask]$

    // $[P0MAT - Port 0 Match]
    /***********************************************************************
     - P0.0 pin logic value is compared with logic HIGH
     - P0.1 pin logic value is compared with logic HIGH
     - P0.2 pin logic value is compared with logic HIGH
     - P0.3 pin logic value is compared with logic HIGH
     - P0.4 pin logic value is compared with logic HIGH
     - P0.5 pin logic value is compared with logic HIGH
     - P0.6 pin logic value is compared with logic LOW
     - P0.7 pin logic value is compared with logic LOW
     ***********************************************************************/
    P0MAT = P0MAT_B0__HIGH | P0MAT_B1__HIGH | P0MAT_B2__HIGH | P0MAT_B3__HIGH
            | P0MAT_B4__HIGH | P0MAT_B5__HIGH | P0MAT_B6__LOW | P0MAT_B7__LOW;
    // [P0MAT - Port 0 Match]$

    // $[P0DRV - Port 0 Drive Strength]
    // [P0DRV - Port 0 Drive Strength]$
}

extern void PBCFG_0_enter_DefaultMode_from_RESET(void)
{
    // $[XBR2 - Port I/O Crossbar 2]
    /***********************************************************************
     - Weak Pullups disabled
     - Crossbar enabled
     ***********************************************************************/
    XBR2 = XBR2_WEAKPUD__PULL_UPS_DISABLED | XBR2_XBARE__ENABLED;
    // [XBR2 - Port I/O Crossbar 2]$

    // $[XBR0 - Port I/O Crossbar 0]
    /***********************************************************************
     - UART TX, RX routed to Port pins P0.4 and P0.5
     - SPI I/O unavailable at Port pins
     - SMBus 0 I/O unavailable at Port pins
     - CP0 unavailable at Port pin
     - Asynchronous CP0 unavailable at Port pin
     - SYSCLK unavailable at Port pin
     ***********************************************************************/
    XBR0 = XBR0_URT0E__ENABLED | XBR0_SPI0E__DISABLED | XBR0_SMB0E__DISABLED
            | XBR0_CP0E__DISABLED | XBR0_CP0AE__DISABLED
            | XBR0_SYSCKE__DISABLED;
    // [XBR0 - Port I/O Crossbar 0]$

    // $[XBR1 - Port I/O Crossbar 1]
    // [XBR1 - Port I/O Crossbar 1]$

    // $[XBR1 - Port I/O Crossbar 1]
    // [XBR1 - Port I/O Crossbar 1]$
}

extern void PCA_0_enter_DefaultMode_from_RESET(void)
{
    // $[PCA0MD - PCA Mode]
    /***********************************************************************
     - Disable Watchdog Timer
     - System clock divided by 12
     - PCA continues to function normally while the system controller is in
     Idle Mode
     - Disable the CF interrupt
     - Disable Watchdog Timer
     - Watchdog Timer Enable unlocked
     ***********************************************************************/
    SFRPAGE = 0x00;
    PCA0MD &= ~PCA0MD_WDTE__BMASK;
    PCA0MD = PCA0MD_CPS__SYSCLK_DIV_12 | PCA0MD_CIDL__NORMAL
            | PCA0MD_ECF__OVF_INT_DISABLED | PCA0MD_WDTE__DISABLED
            | PCA0MD_WDLCK__UNLOCKED;
    // [PCA0MD - PCA Mode]$

    // $[PCA0H - PCA Counter/Timer High Byte]
    // [PCA0H - PCA Counter/Timer High Byte]$

    // $[PCA0L - PCA Counter/Timer Low Byte]
    // [PCA0L - PCA Counter/Timer Low Byte]$

    // $[PCA0PWM - PCA PWM Configuration]
    // [PCA0PWM - PCA PWM Configuration]$

    // $[PCA0CN0 - PCA Control 0]
    // [PCA0CN0 - PCA Control 0]$
}

extern void PCACH_2_enter_DefaultMode_from_RESET(void)
{
    // $[PCA0 Settings Save]
    // Select Capture/Compare register)
    PCA0PWM &= ~PCA0PWM_ARSEL__BMASK;
    // [PCA0 Settings Save]$

    // $[PCA0CPM2 - PCA Channel 2 Capture/Compare Mode]
    /***********************************************************************
     - Disable negative edge capture
     - Disable CCF2 interrupts
     - Enable match function
     - 8 to 11-bit PWM selected
     - Disable positive edge capture
     - Disable comparator function
     - Disable PWM function
     - Disable toggle function
     ***********************************************************************/
    PCA0CPM2 = PCA0CPM2_CAPN__DISABLED | PCA0CPM2_ECCF__DISABLED
            | PCA0CPM2_MAT__ENABLED | PCA0CPM2_PWM16__8_BIT
            | PCA0CPM2_CAPP__DISABLED | PCA0CPM2_ECOM__DISABLED
            | PCA0CPM2_PWM__DISABLED | PCA0CPM2_TOG__DISABLED;
    // [PCA0CPM2 - PCA Channel 2 Capture/Compare Mode]$

    // $[PCA0CPL2 - PCA Channel 2 Capture Module Low Byte]
    // [PCA0CPL2 - PCA Channel 2 Capture Module Low Byte]$

    // $[PCA0CPH2 - PCA Channel 2 Capture Module High Byte]
    PCA0CPH2 = 0x00;
    // [PCA0CPH2 - PCA Channel 2 Capture Module High Byte]$

    // $[Auto-reload]
    // [Auto-reload]$

    // $[PCA0 Settings Restore]
    // [PCA0 Settings Restore]$
}

extern void INTERRUPT_0_enter_DefaultMode_from_RESET(void)
{
    // $[EIE1 - Extended Interrupt Enable 1]
    /***********************************************************************
     - Disable ADC0 Conversion Complete interrupt
     - Disable ADC0 Window Comparison interrupt
     - Disable CP0 interrupts
     - Disable all PCA0 interrupts
     - Disable RTC Alarm interrupts
     - Disable all SMB0 interrupts
     - Enable interrupt requests generated by the TF3L or TF3H flags
     ***********************************************************************/
    EIE1 = EIE1_EADC0__DISABLED | EIE1_EWADC0__DISABLED | EIE1_ECP0__DISABLED
            | EIE1_EPCA0__DISABLED | EIE1_ERTC0A__DISABLED
            | EIE1_ESMB0__DISABLED | EIE1_ET3__ENABLED;
    // [EIE1 - Extended Interrupt Enable 1]$

    // $[EIP1 - Extended Interrupt Priority 1]
    // [EIP1 - Extended Interrupt Priority 1]$

    // $[IE - Interrupt Enable]
    /***********************************************************************
     - Disable all interrupt sources
     - Disable external interrupt 0
     - Disable external interrupt 1
     - Disable all SPI0 interrupts
     - Enable interrupt requests generated by the TF0 flag
     - Enable interrupt requests generated by the TF1 flag
     - Enable interrupt requests generated by the TF2L or TF2H flags
     - Disable UART0 interrupt
     ***********************************************************************/
    IE = IE_EA__DISABLED | IE_EX0__DISABLED | IE_EX1__DISABLED
            | IE_ESPI0__DISABLED | IE_ET0__ENABLED | IE_ET1__ENABLED
            | IE_ET2__ENABLED | IE_ES0__DISABLED;
    // [IE - Interrupt Enable]$

    // $[IP - Interrupt Priority]
    // [IP - Interrupt Priority]$

    // $[EIE2 - Extended Interrupt Enable 2]
    /***********************************************************************
     - Disable Capacitive Sense Conversion Complete interrupt
     - Disable Capacitive Sense Digital Comparator interrupt
     - Disable Capacitive Sense End of Scan interrupt
     - Enable interrupt requests generated by a Port Match
     - Disable RTC Oscillator Fail interrupts
     - Disable the Supply Monitor Early Warning interrupt
     ***********************************************************************/
    EIE2 = EIE2_ECSCPT__DISABLED | EIE2_ECSDC__DISABLED | EIE2_ECSEOS__DISABLED
            | EIE2_EMAT__ENABLED | EIE2_ERTC0F__DISABLED | EIE2_EWARN__DISABLED;
    // [EIE2 - Extended Interrupt Enable 2]$

    // $[EIP2 - Extended Interrupt Priority 2]
    // [EIP2 - Extended Interrupt Priority 2]$
}

extern void TIMER_SETUP_0_enter_DefaultMode_from_RESET(void)
{
    // $[CKCON0 - Clock Control 0]
    /***********************************************************************
     - System clock divided by 48
     - Counter/Timer 0 uses the clock defined by the prescale field, SCA
     - Timer 2 high byte uses the clock defined by T2XCLK in TMR2CN0
     - Timer 2 low byte uses the clock defined by T2XCLK in TMR2CN0
     - Timer 3 high byte uses the clock defined by T3XCLK in TMR3CN0
     - Timer 3 low byte uses the clock defined by T3XCLK in TMR3CN0
     - Timer 1 uses the system clock
     ***********************************************************************/
    CKCON0 = CKCON0_SCA__SYSCLK_DIV_48 | CKCON0_T0M__PRESCALE
            | CKCON0_T2MH__EXTERNAL_CLOCK | CKCON0_T2ML__EXTERNAL_CLOCK
            | CKCON0_T3MH__EXTERNAL_CLOCK | CKCON0_T3ML__EXTERNAL_CLOCK
            | CKCON0_T1M__SYSCLK;
    // [CKCON0 - Clock Control 0]$

    // $[TMOD - Timer 0/1 Mode]
    /***********************************************************************
     - Mode 1, 16-bit Counter/Timer
     - Mode 2, 8-bit Counter/Timer with Auto-Reload
     - Timer Mode
     - Timer 0 enabled when TR0 = 1 irrespective of INT0 logic level
     - Timer Mode
     - Timer 1 enabled when TR1 = 1 irrespective of INT1 logic level
     ***********************************************************************/
    TMOD = TMOD_T0M__MODE1 | TMOD_T1M__MODE2 | TMOD_CT0__TIMER
            | TMOD_GATE0__DISABLED | TMOD_CT1__TIMER | TMOD_GATE1__DISABLED;
    // [TMOD - Timer 0/1 Mode]$

    // $[TCON - Timer 0/1 Control]
    /***********************************************************************
     - Start Timer 1 running
     ***********************************************************************/
    TCON |= TCON_TR1__RUN;
    // [TCON - Timer 0/1 Control]$

    // $[TCON - Timer 0/1 Control]
    // [TCON - Timer 0/1 Control]$
}

extern void TIMER01_0_enter_DefaultMode_from_RESET(void)
{
    // $[Timer Initialization]
    //Save Timer Configuration
    uint8_t TCON_save;
    TCON_save = TCON;
    //Stop Timers
    TCON &= ~TCON_TR0__BMASK & ~TCON_TR1__BMASK;

    // [Timer Initialization]$

    // $[TH0 - Timer 0 High Byte]
    // [TH0 - Timer 0 High Byte]$

    // $[TL0 - Timer 0 Low Byte]
    // [TL0 - Timer 0 Low Byte]$

    // $[TH1 - Timer 1 High Byte]
    /***********************************************************************
     - Timer 1 High Byte = 0xA9
     ***********************************************************************/
    TH1 = (0xA9 << TH1_TH1__SHIFT);
    // [TH1 - Timer 1 High Byte]$

    // $[TL1 - Timer 1 Low Byte]
    // [TL1 - Timer 1 Low Byte]$

    // $[Timer Restoration]
    //Restore Timer Configuration
    TCON |= (TCON_save & TCON_TR0__BMASK) | (TCON_save & TCON_TR1__BMASK);

    // [Timer Restoration]$
}
extern void CMP_0_enter_DefaultMode_from_RESET(void)
{
    // $[CMP0MX - Comparator 0 Multiplexer Selection]
    /***********************************************************************
     - External pin CMP0P.4
     - VDD divided by 2
     ***********************************************************************/
    uint8_t delay;

    CMP0MX = CMP0MX_CMXP__CMP0P4 | CMP0MX_CMXN__VDD_DIV_2;
    // Delay to allow the comparator inputs to settle
    for (delay = 0; delay < 0x20; delay++)
        ;
    // [CMP0MX - Comparator 0 Multiplexer Selection]$

    // $[CMP0MD - Comparator 0 Mode]
    /***********************************************************************
     - Mode 0
     - Comparator falling-edge interrupt enabled
     ***********************************************************************/
    CMP0MD &= ~CMP0MD_CPMD__FMASK;
    CMP0MD |= CMP0MD_CPFIE__FALL_INT_ENABLED;
    // [CMP0MD - Comparator 0 Mode]$

    // $[CMP0CN0 - Comparator 0 Control 0]
    /***********************************************************************
     - Comparator enabled
     - Positive Hysteresis = Hysteresis 3
     - Negative Hysteresis = Hysteresis 3
     ***********************************************************************/
    CMP0CN0 |= CMP0CN0_CPEN__ENABLED | CMP0CN0_CPHYP__ENABLED_MODE3
            | CMP0CN0_CPHYN__ENABLED_MODE3;
    // [CMP0CN0 - Comparator 0 Control 0]$

}
extern void CLOCK_0_enter_DefaultMode_from_RESET(void)
{
    // $[CLKSEL - Clock Select]
    /***********************************************************************
     - SYSCLK is equal to selected clock source divided by 1
     - Clock derived from the Internal Low Power Oscillator
     ***********************************************************************/
    CLKSEL = CLKSEL_CLKDIV__SYSCLK_DIV_1 | CLKSEL_CLKSL__LPOSC;
    // Wait for the clock to be ready
    while ((CLKSEL & CLKSEL_CLKRDY__BMASK) != CLKSEL_CLKRDY__SET)
        ;
    // [CLKSEL - Clock Select]$

}

