//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

/*
 * Copyright (c) 2019-2020, NVIDIA CORPORATION.  All rights reserved.
 *
 * NVIDIA CORPORATION and its licensors retain all intellectual property
 * and proprietary rights in and to this software, related documentation
 * and any modifications thereto.  Any use, reproduction, disclosure or
 * distribution of this software and related documentation without an express
 * license agreement from NVIDIA CORPORATION is strictly prohibited.
 */

// USER INCLUDES
#include "gpio.h"
#include "timer.h"

static uint8_t debounce_enable_mask = 0x00;
volatile bit timer1_flag;
volatile bit timer0_flag;

void pin_state_change_kick(void)
{
    TMR3H = TIMER3_KICK_RELOAD_HIGH;
    TMR3L = TIMER3_KICK_RELOAD_LOW;
    TMR3CN0 |= TMR3CN0_TR3__RUN;
}

//-----------------------------------------------------------------------------
// TIMER0_ISR
//-----------------------------------------------------------------------------
//
// TIMER0 ISR Content goes here. Remember to clear flag bits:
// TCON::TF0 (Timer 0 Overflow Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT(TIMER0_ISR, TIMER0_IRQn) // PWR_BTN_N sec counter
{
    TCON_TF0 = 0; // clear interrupt flag
    TCON_TR0 = 0; // stop timer
    timer0_flag = 1;
}

//-----------------------------------------------------------------------------
// TIMER1_ISR
//-----------------------------------------------------------------------------
//
// TIMER1 ISR Content goes here. Remember to clear flag bits:
// TCON::TF1 (Timer 1 Overflow Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT(TIMER1_ISR, TIMER1_IRQn) // pin control delay
{
    TCON_TF1 = 0; // clear interrupt flag
    TCON_TR1 = 0; // stop timer
    timer1_flag = 1;
}

//-----------------------------------------------------------------------------
// TIMER2_ISR
//-----------------------------------------------------------------------------
//
// TIMER2 ISR Content goes here. Remember to clear flag bits:
// TMR2CN0::TF2H (Timer # High Byte Overflow Flag)
// TMR2CN0::TF2L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT(TIMER2_ISR, TIMER2_IRQn) // debouncing
{
    static uint8_t BTN_STATE_PWR_BTN_N = 0xFF;
    static uint8_t BTN_STATE_VOL_UP_N = 0xFF;
    static uint8_t BTN_STATE_ACOK = 0x00;
    uint8_t save_debounce_enable_mask = debounce_enable_mask;

    TMR2CN0_TF2H = 0; // clear interrupt flag
    TMR2CN0_TR2 = 0;  // stop timer 2
    TMR2H = TIMER2_DEBOUNCE_RELOAD_HIGH;
    TMR2L = TIMER2_DEBOUNCE_RELOAD_LOW;
    TMR2CN0_TR2 = 1; // start timer 2

    // PWR_BTN_N
    if (debounce_enable_mask & PIN_STATE_MASK_PWR_BTN_N)
    {
        BTN_STATE_PWR_BTN_N = (BTN_STATE_PWR_BTN_N << 1) | PWR_BTN_N | DEBOUNCE_STATE_MASK;

        if (BTN_STATE_PWR_BTN_N == DEBOUNCE_STATE_HIGH_MATCH)
        {
            debounce_enable_mask &= ~PIN_STATE_MASK_PWR_BTN_N;
            pin_state |= PIN_STATE_MASK_PWR_BTN_N;
            P0MAT |= P0MASK_PWR_BTN_N; // enable port match falling edge
            P0MASK |= P0MASK_PWR_BTN_N;
            PB_BUFF_N = 1;
        }
        else if (BTN_STATE_PWR_BTN_N == DEBOUNCE_STATE_LOW_MATCH)
        {
            debounce_enable_mask &= ~PIN_STATE_MASK_PWR_BTN_N;
            pin_state &= ~(PIN_STATE_MASK_PWR_BTN_N);
            P0MAT &= ~(P0MASK_PWR_BTN_N); // enable port match rising edge
            P0MASK |= P0MASK_PWR_BTN_N;
            PB_BUFF_N = 0;
        }
        else
        {
            // do nothing
        }
    }

    // ACOK
    if (debounce_enable_mask & PIN_STATE_MASK_ACOK)
    {
        BTN_STATE_ACOK = (BTN_STATE_ACOK << 1) | ACOK | DEBOUNCE_STATE_MASK;

        if (BTN_STATE_ACOK == DEBOUNCE_STATE_HIGH_MATCH)
        {
            debounce_enable_mask &= ~PIN_STATE_MASK_ACOK;
            pin_state |= PIN_STATE_MASK_ACOK;
            P0MAT |= P0MASK_ACOK; // enable port match falling edge
            P0MASK |= P0MASK_ACOK;
        }
        else if (BTN_STATE_ACOK == DEBOUNCE_STATE_LOW_MATCH)
        {
            debounce_enable_mask &= ~PIN_STATE_MASK_ACOK;
            pin_state &= ~(PIN_STATE_MASK_ACOK);
            P0MAT &= ~(P0MASK_ACOK); // enable port match rising edge
            P0MASK |= P0MASK_ACOK;
        }
        else
        {
            // do nothing
        }
    }

    // VOL_UP_N
    if (debounce_enable_mask & PIN_STATE_MASK_VOL_UP_N)
    {
        BTN_STATE_VOL_UP_N = (BTN_STATE_VOL_UP_N << 1) | VOL_UP_N | DEBOUNCE_STATE_MASK;

        if (BTN_STATE_VOL_UP_N == DEBOUNCE_STATE_HIGH_MATCH)
        {
            debounce_enable_mask &= ~PIN_STATE_MASK_VOL_UP_N;
            pin_state |= PIN_STATE_MASK_VOL_UP_N;
            P0MAT |= P0MASK_VOL_UP_N; // enable port match falling edge
            P0MASK |= P0MASK_VOL_UP_N;
        }
        else if (BTN_STATE_VOL_UP_N == DEBOUNCE_STATE_LOW_MATCH)
        {
            debounce_enable_mask &= ~PIN_STATE_MASK_VOL_UP_N;
            pin_state &= ~(PIN_STATE_MASK_VOL_UP_N);
            P0MAT &= ~(P0MASK_VOL_UP_N); // enable port match rising edge
            P0MASK |= P0MASK_VOL_UP_N;
        }
        else
        {
            // do nothing
        }
    }

    if (debounce_enable_mask == 0x00)
    {
        TMR2CN0_TR2 = 0; // if there's no button needs debouncing, stop timer 2
    }

    if (save_debounce_enable_mask != debounce_enable_mask)
    {
        // if both PWR_BTN_N and VOL_UP_N are asserted, assert FORCE_RECOVERY_N
        FORCE_RECOVERY_N = (bit)(pin_state & (PIN_STATE_MASK_PWR_BTN_N | PIN_STATE_MASK_VOL_UP_N));
        // pin_state changed, wake up the MCU to check pin_state again
        pin_state_change_kick();
    }
}

//-----------------------------------------------------------------------------
// PMATCH_ISR
//-----------------------------------------------------------------------------
//
// PMATCH ISR Content goes here. Remember to clear flag bits:

//
//-----------------------------------------------------------------------------
SI_INTERRUPT(PMATCH_ISR, PMATCH_IRQn)
{
    uint8_t matched_pins;
    uint8_t current_signal_pin_state;

    EIE2 &= ~(EIE2_EMAT__ENABLED); // disable Port Match in case of triggering multiple times
    current_signal_pin_state = get_signal_pin_state();
    matched_pins = pin_state ^ current_signal_pin_state;

    if (matched_pins & PIN_STATE_NO_DEBOUNCE_PIN_MASK)
    {   // pins that need port match
        if (matched_pins & PIN_STATE_MASK_PWR_GOOD)
        {
            P0MAT ^= P0MASK_PWR_GOOD;
        }
        if (matched_pins & PIN_STATE_MASK_RESET_N)
        {
            P1MAT ^= P1MASK_RESET_N;
        }

        pin_state_change_kick();
    }
    else
    {   // pins that need port match debouncing
        // if port match is enabled and the pin value changed
        if ((P0MASK & P0MASK_PWR_BTN_N) && ((bit)(pin_state & PIN_STATE_MASK_PWR_BTN_N) != PWR_BTN_N))
        {
            debounce_enable_mask |= PIN_STATE_MASK_PWR_BTN_N; // disable port match and start debouncing
            P0MASK &= ~(P0MASK_PWR_BTN_N);
        }

        if ((P0MASK & P0MASK_ACOK) && ((bit)(pin_state & PIN_STATE_MASK_ACOK) != ACOK))
        {
            debounce_enable_mask |= PIN_STATE_MASK_ACOK; // disable port match and start debouncing
            P0MASK &= ~(P0MASK_ACOK);
        }

        if ((P0MASK & P0MASK_VOL_UP_N) && ((bit)(pin_state & PIN_STATE_MASK_VOL_UP_N) != VOL_UP_N))
        {
            debounce_enable_mask |= PIN_STATE_MASK_VOL_UP_N; // disable port match and start debouncing
            P0MASK &= ~(P0MASK_VOL_UP_N);
        }

        if (debounce_enable_mask && (!TMR2CN0_TR2)) // if timer2 is not running
        {
            TMR2H = 0xFF; // Start timer2 right away to get the first sample
            TMR2L = 0xFF;
            TMR2CN0_TR2 = 1;
        }
    }

    pin_state = current_signal_pin_state; // update pin_state
    EIE2 |= EIE2_EMAT__ENABLED; // enable Port Match
}
//-----------------------------------------------------------------------------
// CMP0_ISR
//-----------------------------------------------------------------------------
//
// CMP0 ISR Content goes here. Remember to clear flag bits:
// CMP0CN0::CPFIF (Comparator Falling-Edge Flag)
// CMP0CN0::CPRIF (Comparator Rising-Edge Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (CMP0_ISR, CMP0_IRQn)
{   // Only trigger in falling edge
    EIE1 &= ~EIE1_ECP0__ENABLED; // Disable comparator interrupt until entering power on state
    CMP0CN0 &= ~CMP0CN0_CPFIF__FALLING_EDGE; // clear interrupt flag
    pin_state &= ~PIN_STATE_MASK_FORCE_SHUTDOWN_N;

    pin_state_change_kick();
}
//-----------------------------------------------------------------------------
// TIMER3_ISR
//-----------------------------------------------------------------------------
//
// TIMER3 ISR Content goes here. Remember to clear flag bits:
// TMR3CN0::TF3H (Timer # High Byte Overflow Flag)
// TMR3CN0::TF3L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER3_ISR, TIMER3_IRQn)
{
    TMR3CN0 &= ~(TMR3CN0_TF3H__SET | TMR3CN0_TF3L__SET); // clear interrupt flags
    TMR3CN0 &= ~TMR3CN0_TR3__RUN; // stop timer
}
